export const TRANSPARENT_COLOR_SECUNDARY = '#1a202ce3'
export const HEADER_HEIGHT = '3.8rem'
export const Z_FIXED_100 = '100'

export const BIGGEST_FONT_SIZE = '2.5rem'
export const H1_FONT_SIZE = '1.75rem'
export const H2_FONT_SIZE = '1.25rem'
export const H3_FONT_SIZE = '1.125rem'
export const NORMAL_FONT_SIZE = '.938rem'
export const SMALL_FONT_SIZE = '.813rem'
export const SMALLER_FONT_SIZE = '.75rem'
export const FONT_REGULAR = '300'
export const FONT_MEDIUM = '400'
export const FONT_SEMI_BOLD = '500'
export const FIRST_COLOR = '#24d0e7'